services:
  swk5-nextstop:
    image: swk5-nextstop
    build:
      context: .
      dockerfile: SWK5-NextStop/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=postgres;Username=postgres;Password=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    depends_on:
      postgres:
        condition: service_healthy
      
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5
        
  frontend:
    build:
      context: /Users/jack/Public/SWK5-NextStop-Client/swk5-nextstop
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "4200:80"
    depends_on:
      - swk5-nextstop

volumes:
  postgres_data: